package com.selmec.plantaselmec.Models;
// Generated Oct 30, 2014 5:43:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cariles generated by hbm2java
 */
@Entity
@Table(name="cariles"
    ,catalog="casetapruebas"
    , uniqueConstraints = {@UniqueConstraint(columnNames="equipo"), @UniqueConstraint(columnNames="NoCarril"), @UniqueConstraint(columnNames="planta")} 
)
public class Cariles  implements java.io.Serializable {


     private Integer id;
     private int noCarril;
     private String equipo;
     private String planta;
     private Integer minCap;
     private Integer maxCap;
     private String descripcion;
     private Set ensamblebases = new HashSet(0);

    public Cariles() {
    }

	
    public Cariles(int noCarril, String equipo, String planta) {
        this.noCarril = noCarril;
        this.equipo = equipo;
        this.planta = planta;
    }
    public Cariles(int noCarril, String equipo, String planta, Integer minCap, Integer maxCap, String descripcion, Set ensamblebases) {
       this.noCarril = noCarril;
       this.equipo = equipo;
       this.planta = planta;
       this.minCap = minCap;
       this.maxCap = maxCap;
       this.descripcion = descripcion;
       this.ensamblebases = ensamblebases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="NoCarril", unique=true, nullable=false)
    public int getNoCarril() {
        return this.noCarril;
    }
    
    public void setNoCarril(int noCarril) {
        this.noCarril = noCarril;
    }

    
    @Column(name="equipo", unique=true, nullable=false, length=45)
    public String getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(String equipo) {
        this.equipo = equipo;
    }

    
    @Column(name="planta", unique=true, nullable=false, length=45)
    public String getPlanta() {
        return this.planta;
    }
    
    public void setPlanta(String planta) {
        this.planta = planta;
    }

    
    @Column(name="minCap")
    public Integer getMinCap() {
        return this.minCap;
    }
    
    public void setMinCap(Integer minCap) {
        this.minCap = minCap;
    }

    
    @Column(name="maxCap")
    public Integer getMaxCap() {
        return this.maxCap;
    }
    
    public void setMaxCap(Integer maxCap) {
        this.maxCap = maxCap;
    }

    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cariles")
    public Set getEnsamblebases() {
        return this.ensamblebases;
    }
    
    public void setEnsamblebases(Set ensamblebases) {
        this.ensamblebases = ensamblebases;
    }




}


