package com.selmec.plantaselmec.Models;
// Generated 14/10/2014 10:35:51 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cariles generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Entity
@Table(name = "cariles", catalog = "test", uniqueConstraints = @UniqueConstraint(columnNames = "NoCarril")
)
public class Cariles implements java.io.Serializable {

    private Integer id;
    private int noCarril;
    private Set ensambles = new HashSet(0);
    private String planta;
    private String equipo;

    public Cariles() {
    }

    public Cariles(int noCarril) {
        this.noCarril = noCarril;
    }

    public Cariles(int noCarril, Set ensambles) {
        this.noCarril = noCarril;
        this.ensambles = ensambles;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "NoCarril", unique = true, nullable = false)
    public int getNoCarril() {
        return this.noCarril;
    }

    public void setNoCarril(int noCarril) {
        this.noCarril = noCarril;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cariles")
    public Set getEnsambles() {
        return this.ensambles;
    }

    public void setEnsambles(Set ensambles) {
        this.ensambles = ensambles;
    }

    @Column(name = "equipo", unique = true, nullable = false)
    public String getEquipo() {
        return this.equipo;
    }

    public void setEquipo(String equipo) {
        this.equipo = equipo;
    }

    @Column(name = "planta", unique = true, nullable = false)
    public String getPlanta() {
        return this.planta;
    }

    public void setPlanta(String planta) {
        this.planta = planta;
    }

}
