package com.selmec.plantaselmec.Models;
// Generated Oct 30, 2014 5:43:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="casetapruebas"
)
public class Clientes  implements java.io.Serializable {


     private Integer id;
     private String razonSocial;
     private String noCliente;
     private String clientescol;
     private Set ubicacioneses = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public Clientes(String razonSocial, String noCliente, String clientescol, Set ubicacioneses) {
       this.razonSocial = razonSocial;
       this.noCliente = noCliente;
       this.clientescol = clientescol;
       this.ubicacioneses = ubicacioneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="razonSocial", nullable=false, length=200)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    
    @Column(name="noCliente", length=45)
    public String getNoCliente() {
        return this.noCliente;
    }
    
    public void setNoCliente(String noCliente) {
        this.noCliente = noCliente;
    }

    
    @Column(name="clientescol", length=45)
    public String getClientescol() {
        return this.clientescol;
    }
    
    public void setClientescol(String clientescol) {
        this.clientescol = clientescol;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientes")
    public Set getUbicacioneses() {
        return this.ubicacioneses;
    }
    
    public void setUbicacioneses(Set ubicacioneses) {
        this.ubicacioneses = ubicacioneses;
    }




}


