package com.selmec.plantaselmec.Models;
// Generated Oct 20, 2014 11:12:41 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Incidencias generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Entity
@Table(name="incidencias"
    ,catalog="test"
)
public class Incidencias  implements java.io.Serializable {


     private String id;
     private String descripcion;
     private Set pruebas = new HashSet(0);

    public Incidencias() {
    }

	
    public Incidencias(String id) {
        this.id = id;
    }
    public Incidencias(String id, String descripcion, Set pruebas) {
       this.id = id;
       this.descripcion = descripcion;
       this.pruebas = pruebas;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, length=45)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="Descripcion", length=250)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="incidencias")
    public Set getPruebas() {
        return this.pruebas;
    }
    
    public void setPruebas(Set pruebas) {
        this.pruebas = pruebas;
    }




}


