package com.selmec.plantaselmec.Models;
// Generated 9/10/2014 05:59:14 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;

/**
 * Lecturas generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class Lecturas  implements java.io.Serializable {


     private int id;
     private Date timeStamp;
     private Prueba prueba;
     private Double l1l2;
     private Double l2l3;
     private Double l3l1;
     private Double hz;
     private Integer temp;
     private Double l1;
     private Double l2;
     private Double l3;

    public Lecturas() {
    }

	
    public Lecturas(int id) {
        this.id = id;
    }
    public Lecturas(int id, Prueba prueba, Double l1l2, Double l2l3, Double l3l1, Double hz, Integer temp, Double l1, Double l2, Double l3) {
       this.id = id;
       this.prueba = prueba;
       this.l1l2 = l1l2;
       this.l2l3 = l2l3;
       this.l3l1 = l3l1;
       this.hz = hz;
       this.temp = temp;
       this.l1 = l1;
       this.l2 = l2;
       this.l3 = l3;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }
    public Prueba getPrueba() {
        return this.prueba;
    }
    
    public void setPrueba(Prueba prueba) {
        this.prueba = prueba;
    }
    public Double getL1l2() {
        return this.l1l2;
    }
    
    public void setL1l2(Double l1l2) {
        this.l1l2 = l1l2;
    }
    public Double getL2l3() {
        return this.l2l3;
    }
    
    public void setL2l3(Double l2l3) {
        this.l2l3 = l2l3;
    }
    public Double getL3l1() {
        return this.l3l1;
    }
    
    public void setL3l1(Double l3l1) {
        this.l3l1 = l3l1;
    }
    public Double getHz() {
        return this.hz;
    }
    
    public void setHz(Double hz) {
        this.hz = hz;
    }
    public Integer getTemp() {
        return this.temp;
    }
    
    public void setTemp(Integer temp) {
        this.temp = temp;
    }
    public Double getL1() {
        return this.l1;
    }
    
    public void setL1(Double l1) {
        this.l1 = l1;
    }
    public Double getL2() {
        return this.l2;
    }
    
    public void setL2(Double l2) {
        this.l2 = l2;
    }
    public Double getL3() {
        return this.l3;
    }
    
    public void setL3(Double l3) {
        this.l3 = l3;
    }
  


}


