package com.selmec.plantaselmec.Models;
// Generated Oct 21, 2014 4:26:41 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Pruebacarga generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Entity
@Table(name = "pruebacarga", catalog = "test"
)
@PrimaryKeyJoinColumn(name = "id")
public class Pruebacarga extends Prueba implements java.io.Serializable {

//    private int id;
//    private Prueba prueba;
    private Double vmax;
    private Double vmin;
    private Double hmax;
    private Double hmin;

    public Pruebacarga() {
    }

    public Pruebacarga(//Prueba prueba,
            Double vmax, Double vmin, Double hmax, Double hmin) {
        //this.prueba = prueba;
        this.vmax = vmax;
        this.vmin = vmin;
        this.hmax = hmax;
        this.hmin = hmin;
    }

//    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "prueba"))
//    @Id
//    @GeneratedValue(generator = "generator")
//
//    @Column(name = "id", unique = true, nullable = false)
//    public int getId() {
//        return this.id;
//    }
//
//    public void setId(int id) {
//        this.id = id;
//    }
//
//    @OneToOne
//    @PrimaryKeyJoinColumn
//    public Prueba getPrueba() {
//        return this.prueba;
//    }
//
//    public void setPrueba(Prueba prueba) {
//        this.prueba = prueba;
//    }
    @Column(name = "vmax", precision = 22, scale = 0)
    public Double getVmax() {
        return this.vmax;
    }

    public void setVmax(Double vmax) {
        this.vmax = vmax;
    }

    @Column(name = "vmin", precision = 22, scale = 0)
    public Double getVmin() {
        return this.vmin;
    }

    public void setVmin(Double vmin) {
        this.vmin = vmin;
    }

    @Column(name = "hmax", precision = 22, scale = 0)
    public Double getHmax() {
        return this.hmax;
    }

    public void setHmax(Double hmax) {
        this.hmax = hmax;
    }

    @Column(name = "hmin", precision = 22, scale = 0)
    public Double getHmin() {
        return this.hmin;
    }

    public void setHmin(Double hmin) {
        this.hmin = hmin;
    }

}
