package com.selmec.plantaselmec.Models;
// Generated Oct 30, 2014 5:43:43 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prueba generated by hbm2java
 */
@Entity
@Table(name = "prueba", catalog = "casetapruebas"
)
public class Prueba extends Pruebabase implements java.io.Serializable {

    private Ensamble ensamble;
    private Pruebabase pruebabase;
    private int tipo;
    private EstadoPrueba estatus;
    private Integer aprueba;
    private Date dtAprueba;
    private Integer apruebaSupervisor;
    private Date dtApruebaSupervisor;
    private Set cargasubitas = new HashSet(0);
    private Pruebacontrol pruebacontrol;
    private Pruebacarga pruebacarga;

    public Prueba() {
    }

    public Prueba(Ensamble ensamble, Pruebabase pruebabase, int tipo, EstadoPrueba estatus) {
        this.ensamble = ensamble;
        this.pruebabase = pruebabase;
        this.tipo = tipo;
        this.estatus = estatus;
    }

    public Prueba(Ensamble ensamble, Pruebabase pruebabase, int tipo, EstadoPrueba estatus, Integer aprueba, Date dtAprueba, Integer apruebaSupervisor, Date dtApruebaSupervisor, Set cargasubitas, Pruebacontrol pruebacontrol, Pruebacarga pruebacarga) {
        this.ensamble = ensamble;
        this.pruebabase = pruebabase;
        this.tipo = tipo;
        this.estatus = estatus;
        this.aprueba = aprueba;
        this.dtAprueba = dtAprueba;
        this.apruebaSupervisor = apruebaSupervisor;
        this.dtApruebaSupervisor = dtApruebaSupervisor;
        this.cargasubitas = cargasubitas;
        this.pruebacontrol = pruebacontrol;
        this.pruebacarga = pruebacarga;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EnsambleID", nullable = false)
    public Ensamble getEnsamble() {
        return this.ensamble;
    }

    public void setEnsamble(Ensamble ensamble) {
        this.ensamble = ensamble;
    }

//    @OneToOne(fetch = FetchType.LAZY)
//    @PrimaryKeyJoinColumn
//    public Pruebabase getPruebabase() {
//        return this.pruebabase;
//    }
//
//    public void setPruebabase(Pruebabase pruebabase) {
//        this.pruebabase = pruebabase;
//    }
    @Column(name = "Tipo", nullable = false)
    public int getTipo() {
        return this.tipo;
    }

    public void setTipo(int tipo) {
        this.tipo = tipo;
    }

    @Column(name = "Estatus", nullable = false)
    public EstadoPrueba getEstatus() {
        return this.estatus;
    }

    public void setEstatus(EstadoPrueba estatus) {
        this.estatus = estatus;
    }

    @Column(name = "Aprueba")
    public Integer getAprueba() {
        return this.aprueba;
    }

    public void setAprueba(Integer aprueba) {
        this.aprueba = aprueba;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dtAprueba", length = 19)
    public Date getDtAprueba() {
        return this.dtAprueba;
    }

    public void setDtAprueba(Date dtAprueba) {
        this.dtAprueba = dtAprueba;
    }

    @Column(name = "ApruebaSupervisor")
    public Integer getApruebaSupervisor() {
        return this.apruebaSupervisor;
    }

    public void setApruebaSupervisor(Integer apruebaSupervisor) {
        this.apruebaSupervisor = apruebaSupervisor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dtApruebaSupervisor", length = 19)
    public Date getDtApruebaSupervisor() {
        return this.dtApruebaSupervisor;
    }

    public void setDtApruebaSupervisor(Date dtApruebaSupervisor) {
        this.dtApruebaSupervisor = dtApruebaSupervisor;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prueba")
    public Set getCargasubitas() {
        return this.cargasubitas;
    }

    public void setCargasubitas(Set cargasubitas) {
        this.cargasubitas = cargasubitas;
    }

//    @OneToOne(fetch = FetchType.LAZY, mappedBy = "prueba")
//    public Pruebacontrol getPruebacontrol() {
//        return this.pruebacontrol;
//    }
//
//    public void setPruebacontrol(Pruebacontrol pruebacontrol) {
//        this.pruebacontrol = pruebacontrol;
//    }
//
//    @OneToOne(fetch = FetchType.LAZY, mappedBy = "prueba")
//    public Pruebacarga getPruebacarga() {
//        return this.pruebacarga;
//    }
//
//    public void setPruebacarga(Pruebacarga pruebacarga) {
//        this.pruebacarga = pruebacarga;
//    }
}
